// Bundles src/ into the single Tampermonkey userscript, dist/vest-copier.user.js. Rollup keeps the code and its comments
// as written, so the installed script reads like the source.
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync('package.json', 'utf8'));
const header = readFileSync('src/userscript-header.txt', 'utf8').replace('{{version}}', version);

// The panel's stylesheet is a plain .css file, imported as a string.
const cssAsText = {
  name: 'css-as-text',
  transform(code, id) {
    if (!id.endsWith('.css')) return null;
    const text = code.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    return { code: `export default \`\n${text}\`;\n`, map: null };
  },
};

// The version shown in the panel and compared with GitHub's comes from package.json.
const injectVersion = {
  name: 'version',
  transform(code, id) {
    return id.endsWith('/src/config.js') ? { code: code.replace('__VERSION__', `'${version}'`), map: null } : null;
  },
};

// Installs from before v0.38 check for updates at raw.githubusercontent.com/.../main/src/vest-copier.user.js. That path
// keeps the header (all an update check reads) at the current version; their update then downloads the release build,
// whose own header points at the release.
const legacyUpdateCheck = {
  name: 'legacy-update-check',
  writeBundle() {
    const legacy = header
      .replace(
        /(@updateURL\s+).*/,
        '$1https://raw.githubusercontent.com/xAmped/Vest-Copier/main/src/vest-copier.user.js',
      )
      .trimEnd();
    writeFileSync(
      'src/vest-copier.user.js',
      `${legacy}\n\n// Generated by \`npm run build\`: the update check for installs from before v0.38. The script itself is built\n` +
        `// from src/main.js into dist/vest-copier.user.js. Don't edit this file.\n`,
    );
  },
};

export default {
  input: 'src/main.js',
  output: {
    file: 'dist/vest-copier.user.js',
    format: 'iife',
    banner: header,
    // already running on this page (the script was injected twice): leave the first copy alone
    intro: 'if (window.__vestCopier) return;\nwindow.__vestCopier = true;\n',
  },
  // ship the code as written: no dead-code removal (debug switches like SITE_SIM stay in place)
  treeshake: false,
  plugins: [cssAsText, injectVersion, legacyUpdateCheck],
  onwarn(warning, warn) {
    // The modules call each other both ways (the UI renders state, actions re-render the UI); none of them does work at
    // load that needs another, so the cycles are harmless.
    if (warning.code === 'CIRCULAR_DEPENDENCY') return;
    warn(warning);
  },
};
